name: Deploy

on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          command: |
            cd pizza
            
            docker-compose down
            git pull
            
            docker-compose up -d --build
